apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: sgumbe/yolo-latest:1.1.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: client-config-map
          volumeMounts:
            - name: client-data
              mountPath: /data
      volumes:
        - name: client-data
          persistentVolumeClaim:
            claimName: client-pvc
