apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sgumbe/yolo-latest:1.2.0
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: connection-string
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  connection-string: bW9uZ29kYitzcnY6Ly9TR3VtYmU6Wml6YTIwMTUuQGNsdXN0ZXIwLjV5NHRmd24ubW9uZ29kYi5uZXQvV0VFSzEwX0lQP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
